spring: 
  profiles:
    active:
    - dev
---
server:
  # 端口
  port: 10086
  context-path: /
spring:
  profiles: dev
eureka:
  client:
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:${server.port}/eureka
      #defaultZone: http://127.0.0.1:10010/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
---
server:
  # 端口
  port: 10087
  context-path: /
spring:
  profiles: test
eureka:
  client:
    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:${server.port}/eureka
      #defaultZone: http://127.0.0.1:10010/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}